server:
  port: 10220

xmlSourcePath: xmltemplate

ftp:
#  ip: 192.168.8.88
  ip: 59.211.16.162
  port: 16788
  username: dapp
  password: GXjh12#$
  encoding: utf-8
  downloadPath: /file_data_exchange/file_receive/xtba_receive/sft/
  uploadPath: /file_data_exchange/file_send/sft_send/
  zipPath: /Users/suzhenchao/浩云/广西社矫/datapipeapi/src/main/resources/static/zipfile
#  ip: 192.168.2.117
#  port: 21
#  username: anonymous
#  password:
#  downloadPath: /iotmp/home/dapp/file_data_exchange/file_send/sft_send/
#  uploadPath: /iotmp/home/dapp/file_data_exchange/file_receive/xtba_receive/sft/
#  downloadPath: /erp_data/
#  uploadPath: /home/dapp/file_data_exchange/file_receive/xtba_receive/sft/